import type { Session, Package } from "./types";
export const sampleSessions: Session[] = [
  {
    id: "S01",
    identificador: "Cliente A",
    modo: "feminino",
    pacote: "pacote_1",
    data: "2026-02-05",
    revision: 0,
    questionario: {
      objetivo: "Transmitir clareza e presença no trabalho",
    },
    avaliacao: {
      temperamento: {
        primario: "fleumatico",
        secundario: "sanguineo",
        sanguineo_pct: "30",
        colerico_pct: "15",
        melancolico_pct: "15",
        fleumatico_pct: "40",
      },
      visagismo: {
        formato_rosto: "oval",
        posicao_pele: "2",
        posicao_cabelo: "9",
        contraste_graus: "7",
        contraste_faixa: "alto",
      },
      medidas: {
        altura_cm: "166",
        peso_kg: "",
        ombro_cm: "96",
        busto_cm: "91",
        torax_cm: "",
        cintura_cm: "76",
        quadril_cm: "101",
        tronco_cm: "75",
        pernas_cm: "91",
        biotipo_confirmado: "triangulo",
      },
      teste_coloracao: {
        temperatura: "fria",
        intensidade: "media",
        profundidade: "escura",
        vermelhos: "frio",
        contraste_observado: "alto",
      },
      coloracao: {
        cartela: "inverno_frio",
        confirmada_pelo_consultor: "sim",
      },
    },
    paginas: {},
    chat: [],
    audit: [],
    fotos: {},
    referencias: [],
  },
  {
    id: "S02",
    identificador: "Cliente B",
    modo: "feminino",
    pacote: "pacote_2",
    data: "2026-02-12",
    revision: 0,
    questionario: {
      objetivo: "Atualizar a imagem mantendo conforto",
    },
    avaliacao: {
      temperamento: {
        primario: "sanguineo",
        secundario: "colerico",
        sanguineo_pct: "40",
        colerico_pct: "30",
        melancolico_pct: "10",
        fleumatico_pct: "20",
      },
      visagismo: {
        formato_rosto: "retangular",
        posicao_pele: "4",
        posicao_cabelo: "8",
        contraste_graus: "4",
        contraste_faixa: "medio",
      },
      medidas: {
        altura_cm: "171",
        peso_kg: "",
        ombro_cm: "98",
        busto_cm: "96",
        torax_cm: "",
        cintura_cm: "74",
        quadril_cm: "99",
        tronco_cm: "78",
        pernas_cm: "93",
        biotipo_confirmado: "ampulheta",
      },
      teste_coloracao: {
        temperatura: "quente",
        intensidade: "media",
        profundidade: "escura",
        vermelhos: "quente",
        contraste_observado: "medio",
      },
      coloracao: {
        cartela: "outono_escuro",
        confirmada_pelo_consultor: "sim",
      },
    },
    paginas: {},
    chat: [],
    audit: [],
    fotos: {},
    referencias: [],
  },
  {
    id: "S03",
    identificador: "Cliente C",
    modo: "masculino",
    pacote: "pacote_7",
    data: "2026-03-04",
    revision: 0,
    questionario: {
      objetivo: "Harmonizar o vestuário para eventos profissionais",
    },
    avaliacao: {
      temperamento: {
        primario: "colerico",
        secundario: "fleumatico",
        sanguineo_pct: "20",
        colerico_pct: "40",
        melancolico_pct: "10",
        fleumatico_pct: "30",
      },
      visagismo: {
        formato_rosto: "quadrado",
        posicao_pele: "3",
        posicao_cabelo: "9",
        contraste_graus: "6",
        contraste_faixa: "alto",
      },
      medidas: {
        altura_cm: "181",
        peso_kg: "80",
        ombro_cm: "111",
        busto_cm: "",
        torax_cm: "105",
        cintura_cm: "88",
        quadril_cm: "99",
        tronco_cm: "82",
        pernas_cm: "99",
        biotipo_confirmado: "trapezio",
      },
      teste_coloracao: {
        temperatura: "fria",
        intensidade: "media",
        profundidade: "escura",
        vermelhos: "frio",
        contraste_observado: "alto",
      },
      coloracao: {
        cartela: "inverno_escuro",
        confirmada_pelo_consultor: "sim",
      },
    },
    paginas: {},
    chat: [],
    audit: [],
    fotos: {},
    referencias: [],
  },
  {
    id: "S04",
    identificador: "Cliente D",
    modo: "feminino",
    pacote: "pacote_1",
    data: "2026-03-18",
    revision: 0,
    questionario: {
      objetivo: "Explorar combinações de cores no cotidiano",
    },
    avaliacao: {
      temperamento: {
        primario: "melancolico",
        secundario: "fleumatico",
        sanguineo_pct: "10",
        colerico_pct: "15",
        melancolico_pct: "45",
        fleumatico_pct: "30",
      },
      visagismo: {
        formato_rosto: "redondo",
        posicao_pele: "3",
        posicao_cabelo: "5",
        contraste_graus: "2",
        contraste_faixa: "baixo",
      },
      medidas: {
        altura_cm: "160",
        peso_kg: "",
        ombro_cm: "92",
        busto_cm: "90",
        torax_cm: "",
        cintura_cm: "82",
        quadril_cm: "94",
        tronco_cm: "73",
        pernas_cm: "87",
        biotipo_confirmado: "retangulo",
      },
      teste_coloracao: {
        temperatura: "quente",
        intensidade: "clara",
        profundidade: "clara",
        vermelhos: "quente",
        contraste_observado: "baixo",
      },
      coloracao: {
        cartela: "primavera_clara",
        confirmada_pelo_consultor: "nao",
      },
    },
    paginas: {},
    chat: [],
    audit: [],
    fotos: {},
    referencias: [],
  },
  {
    id: "S05",
    identificador: "Cliente E",
    modo: "feminino",
    pacote: "pacote_5",
    data: "2026-04-02",
    revision: 0,
    questionario: {
      objetivo: "Destacar criatividade com praticidade",
    },
    avaliacao: {
      temperamento: {
        primario: "sanguineo",
        secundario: "melancolico",
        sanguineo_pct: "40",
        colerico_pct: "15",
        melancolico_pct: "30",
        fleumatico_pct: "15",
      },
      visagismo: {
        formato_rosto: "oval",
        posicao_pele: "3",
        posicao_cabelo: "7",
        contraste_graus: "4",
        contraste_faixa: "medio",
      },
      medidas: {
        altura_cm: "169",
        peso_kg: "",
        ombro_cm: "102",
        busto_cm: "94",
        torax_cm: "",
        cintura_cm: "75",
        quadril_cm: "92",
        tronco_cm: "77",
        pernas_cm: "92",
        biotipo_confirmado: "triangulo_invertido",
      },
      teste_coloracao: {
        temperatura: "fria",
        intensidade: "suave",
        profundidade: "clara",
        vermelhos: "frio",
        contraste_observado: "medio",
      },
      coloracao: {
        cartela: "verao_suave",
        confirmada_pelo_consultor: "nao",
      },
    },
    paginas: {},
    chat: [],
    audit: [],
    fotos: {},
    referencias: [],
  },
  {
    id: "S06",
    identificador: "Cliente F",
    modo: "masculino",
    pacote: "pacote_3",
    data: "2026-04-16",
    revision: 0,
    questionario: {
      objetivo: "Construir uma imagem acessível e elegante",
    },
    avaliacao: {
      temperamento: {
        primario: "fleumatico",
        secundario: "melancolico",
        sanguineo_pct: "15",
        colerico_pct: "15",
        melancolico_pct: "30",
        fleumatico_pct: "40",
      },
      visagismo: {
        formato_rosto: "retangular",
        posicao_pele: "2",
        posicao_cabelo: "8",
        contraste_graus: "6",
        contraste_faixa: "alto",
      },
      medidas: {
        altura_cm: "175",
        peso_kg: "77",
        ombro_cm: "107",
        busto_cm: "",
        torax_cm: "101",
        cintura_cm: "91",
        quadril_cm: "98",
        tronco_cm: "81",
        pernas_cm: "94",
        biotipo_confirmado: "trapezio",
      },
      teste_coloracao: {
        temperatura: "fria",
        intensidade: "media",
        profundidade: "media",
        vermelhos: "frio",
        contraste_observado: "alto",
      },
      coloracao: {
        cartela: "inverno_frio",
        confirmada_pelo_consultor: "sim",
      },
    },
    paginas: {},
    chat: [],
    audit: [],
    fotos: {},
    referencias: [],
  },
  {
    id: "S07",
    identificador: "Cliente G",
    modo: "feminino",
    pacote: "pacote_1",
    data: "2026-05-07",
    revision: 0,
    questionario: {
      objetivo: "Usar cores suaves com segurança",
    },
    avaliacao: {
      temperamento: {
        primario: "melancolico",
        secundario: "sanguineo",
        sanguineo_pct: "30",
        colerico_pct: "10",
        melancolico_pct: "45",
        fleumatico_pct: "15",
      },
      visagismo: {
        formato_rosto: "hexagonal",
        posicao_pele: "5",
        posicao_cabelo: "7",
        contraste_graus: "2",
        contraste_faixa: "baixo",
      },
      medidas: {
        altura_cm: "163",
        peso_kg: "",
        ombro_cm: "94",
        busto_cm: "91",
        torax_cm: "",
        cintura_cm: "79",
        quadril_cm: "99",
        tronco_cm: "74",
        pernas_cm: "89",
        biotipo_confirmado: "triangulo",
      },
      teste_coloracao: {
        temperatura: "quente",
        intensidade: "suave",
        profundidade: "media",
        vermelhos: "quente",
        contraste_observado: "baixo",
      },
      coloracao: {
        cartela: "outono_suave",
        confirmada_pelo_consultor: "nao",
      },
    },
    paginas: {},
    chat: [],
    audit: [],
    fotos: {},
    referencias: [],
  },
  {
    id: "S08",
    identificador: "Cliente H",
    modo: "feminino",
    pacote: "pacote_9",
    data: "2026-05-21",
    revision: 0,
    questionario: {
      objetivo: "Revisar peças para uma imagem marcante",
    },
    avaliacao: {
      temperamento: {
        primario: "colerico",
        secundario: "sanguineo",
        sanguineo_pct: "30",
        colerico_pct: "40",
        melancolico_pct: "15",
        fleumatico_pct: "15",
      },
      visagismo: {
        formato_rosto: "triangular_invertido",
        posicao_pele: "2",
        posicao_cabelo: "9",
        contraste_graus: "7",
        contraste_faixa: "alto",
      },
      medidas: {
        altura_cm: "172",
        peso_kg: "",
        ombro_cm: "97",
        busto_cm: "95",
        torax_cm: "",
        cintura_cm: "78",
        quadril_cm: "98",
        tronco_cm: "79",
        pernas_cm: "93",
        biotipo_confirmado: "ampulheta",
      },
      teste_coloracao: {
        temperatura: "fria",
        intensidade: "brilhante",
        profundidade: "escura",
        vermelhos: "frio",
        contraste_observado: "alto",
      },
      coloracao: {
        cartela: "inverno_brilhante",
        confirmada_pelo_consultor: "nao",
      },
    },
    paginas: {},
    chat: [],
    audit: [],
    fotos: {},
    referencias: [],
  },
];
export const packages: Package[] = [
  {
    id: "pacote_1",
    nome: "Pacote 1 · Visagismo, Biotipo e Coloração",
    formato: "Presencial",
    paginas: [
      "Perfil e objetivo de imagem",
      "Temperamento",
      "Visagismo — rosto, cabelo e franja",
      "Tipologia física e silhueta",
      "Coloração pessoal",
      "Mini cartela de cores",
    ],
  },
  {
    id: "pacote_2",
    nome: "Pacote 2 · Guia de Estilo Estratégico",
    formato: "Híbrido",
    paginas: [
      "Perfil e objetivo de imagem",
      "Mapeamento de estilo",
      "Composições de looks",
      "Lista de compras sugerida",
      "Styling e comportamento",
    ],
  },
  {
    id: "pacote_3",
    nome: "Pacote 3 · Lookbook de Estilo",
    formato: "Presencial",
    paginas: ["Perfil e objetivo de imagem", "Composições de looks", "Styling e comportamento"],
  },
  {
    id: "pacote_4",
    nome: "Pacote 4 · Personal Shopping",
    formato: "Presencial ou online",
    paginas: [
      "Perfil e objetivo de imagem",
      "Roteiro de personal shopping",
      "Lista de compras sugerida",
    ],
  },
  {
    id: "pacote_5",
    nome: "Pacote 5 · Consultoria Completa — Híbrida",
    formato: "8 encontros",
    paginas: [
      "Perfil e objetivo de imagem",
      "Temperamento",
      "Visagismo — rosto, cabelo e franja",
      "Tipologia física e silhueta",
      "Coloração pessoal",
      "Mini cartela de cores",
      "Mapeamento de estilo",
      "Estilo olfativo",
      "Revitalização do closet",
      "Roteiro de personal shopping",
      "Composições de looks",
      "Styling e comportamento",
    ],
  },
  {
    id: "pacote_6",
    nome: "Pacote 6 · Consultoria Completa — Online",
    formato: "8 encontros online",
    paginas: [
      "Perfil e objetivo de imagem",
      "Temperamento",
      "Visagismo — rosto, cabelo e franja",
      "Tipologia física e silhueta",
      "Coloração pessoal",
      "Mini cartela de cores",
      "Mapeamento de estilo",
      "Estilo olfativo",
      "Revitalização do closet",
      "Roteiro de personal shopping",
      "Composições de looks",
      "Styling e comportamento",
    ],
  },
  {
    id: "pacote_7",
    nome: "Pacote 7 · Estilo Corporativo",
    formato: "Presencial ou online",
    paginas: [
      "Perfil e objetivo de imagem",
      "Posicionamento profissional",
      "Composições de looks",
      "Lista de compras sugerida",
      "Styling e comportamento",
    ],
  },
  {
    id: "pacote_8",
    nome: "Pacote 8 · Mala Planejada",
    formato: "Presencial",
    paginas: ["Perfil e objetivo de imagem", "Mala planejada"],
  },
  {
    id: "pacote_9",
    nome: "Pacote 9 · Styling para Fotos e Eventos",
    formato: "Híbrido",
    paginas: [
      "Perfil e objetivo de imagem",
      "Styling para fotos e eventos",
      "Styling e comportamento",
    ],
  },
];
export const knowledge = [
  {
    arquivo: "01_coloracao_pessoal.md",
    titulo: "coloracao pessoal",
    conteudo:
      '---\ntema: Coloração pessoal\nnivel: 2 (método)\nfontes: Apostilas de Coloração Pessoal 1 e 2 (método Sazonal Expandido, Studio Immagine); Consultoria de Cores\nobservacao: resumo próprio, reescrito; não reproduz o material original\n---\n\n# Coloração pessoal — resumo do método\n\n## O que é (e o que não é)\nColoração pessoal é uma análise **comparativa**: coloca-se tecidos coloridos junto ao rosto e observa-se quais cores harmonizam com a pele, os cabelos e os olhos. Não é julgamento de beleza, não é análise à distância e não é uma lista de proibições. O resultado orienta escolhas conscientes de roupas, maquiagem, cabelo e acessórios, de acordo com a imagem que a pessoa deseja transmitir.\n\nRegra central: **sem comparação não há diagnóstico**. Nenhuma cor é avaliada isolada.\n\n## As três dimensões da cor (TIP)\n- **Temperatura** — quanto de pigmento amarelo (quente) ou azul (frio) a cor tem.\n- **Intensidade (saturação)** — cor pura e viva = intensa/brilhante; cor com cinza ou marrom = suave/opaca.\n- **Profundidade (valor)** — quanto de branco (clara) ou preto (escura) a cor tem.\n\n**Contraste** é diferente de profundidade: mede a diferença de tom entre pele, cabelos e olhos. Pele muito clara com cabelo preto = alto contraste.\n\n## Preparação do teste\n- Luz natural ou lâmpada neutra (entre 4.500 e 5.200 K), espelho, capa e faixa cinza neutras.\n- Cliente sem maquiagem e sem acessórios perto do rosto.\n- Anotar micropigmentação e cabelo tingido, pois interferem no resultado. O cabelo tingido fica coberto pela faixa.\n- Evitar fotos com celulares que alteram muito as cores.\n\n## Roteiro do teste (sequência usada na ficha)\n1. **Contraste** — escala de cinza de 0 a 10 (foto em preto e branco). Marca-se a posição da pele e a do cabelo; a distância entre elas é a graduação.\n   - diferença de 1 a 3 = baixo contraste (claro ou escuro)\n   - 4 a 5 = médio\n   - 6 ou mais = alto\n2. **Profundidade** — comparar tecidos claros e escuros.\n3. **Intensidade** — comparar tecidos suaves e intensos.\n4. **Temperatura** — comparar quente e frio; confirmar o subtom.\n5. **Teste dos vermelhos** — vermelho quente, neutro-quente, neutro-frio e frio. Mostra se a temperatura é característica principal ou secundária.\n6. **Tecidos das 12 estações** — testar só as estações compatíveis com as fases anteriores.\n7. (Opcional) Tecidos estampados das estações.\n\nBoa prática: não antecipar o resultado; se houver dúvida, fotografar com luz natural (com autorização) e revisar.\n\n**Pele oliva** ("falsa quente"): tem fundo amarelado, mas harmoniza com cores frias. Pode aparecer no Verão e no Inverno.\n\n## As 4 famílias e as 12 estações\n| Família | TIP da família | Estações (característica principal) |\n|---|---|---|\n| Verão | fria · suave · clara | Claro (profundidade clara), Frio (temperatura fria), Suave (intensidade suave) |\n| Outono | quente · suave · escura | Suave (intensidade suave), Quente (temperatura quente), Escuro (profundidade escura) |\n| Inverno | fria · brilhante · escura | Escuro (profundidade escura), Frio (temperatura fria), Brilhante (intensidade brilhante) |\n| Primavera | quente · brilhante · clara | Brilhante (intensidade brilhante), Quente (temperatura quente), Clara (profundidade clara) |\n\nCada estação "vizinha" empresta uma característica da família ao lado (ex.: o Verão Claro recebe leveza da Primavera; o Outono Escuro fica próximo do Inverno Escuro, mas com temperatura neutra-quente).\n\n### Detalhe por estação (para as regras e o modelo de ML)\n| Estação | Principal | Secundária | Intensidade | Profundidade | Contraste típico |\n|---|---|---|---|---|---|\n| Verão Claro | clara | neutra-fria | suave a média | clara | baixo claro a médio |\n| Verão Frio | fria | — | suave a média | clara a média | baixo claro a médio |\n| Verão Suave | suave | neutra-fria | suave | clara a média | baixo a médio |\n| Outono Suave | suave | neutra-quente | suave | média a escura | baixo a médio |\n| Outono Quente | quente | — | suave a média-baixa | média a escura | médio a alto, ou baixo escuro |\n| Outono Escuro | escura | neutra-quente | suave a média-alta | escura | baixo escuro a alto |\n| Inverno Escuro | escura | neutra-fria | média a brilhante | escura | baixo escuro a alto |\n| Inverno Frio | fria | — | média a brilhante | média a escura | baixo escuro a alto |\n| Inverno Brilhante | brilhante | neutra-fria | brilhante | média a escura | baixo escuro a alto |\n| Primavera Brilhante | brilhante | neutra-quente | brilhante | clara a média | médio a alto |\n| Primavera Quente | quente | — | média a brilhante | clara a média | baixo claro a médio |\n| Primavera Clara | clara | neutra-quente | baixa a média-alta | clara | baixo claro a médio |\n\n## Metais e acabamentos (tendência por família)\n- **Verão:** prata, ouro branco, rosé suave; acabamentos acetinados e foscos.\n- **Outono:** dourado envelhecido, cobre, bronze; acabamentos foscos.\n- **Inverno:** prata e metais brilhantes; acabamentos com brilho.\n- **Primavera:** dourado claro e brilhante.\n\n## Harmonias cromáticas (para montar looks)\n- **Monocromática:** variações de uma mesma cor.\n- **Análoga:** cores vizinhas no círculo cromático.\n- **Complementar:** cores opostas; gera contraste e destaque.\n- **Tríade:** três cores equidistantes; mais ousada.\nRegra prática de styling: até duas ou três cores principais por look, e as neutras da cartela como base.\n\n## Psicologia das cores (uso na comunicação da imagem)\n- Azul: confiança, calma, credibilidade.\n- Vermelho: energia, paixão, poder.\n- Verde: equilíbrio, natureza, renovação.\n- Amarelo: alegria, otimismo, comunicação.\n- Preto: autoridade, sofisticação.\n- Branco: leveza, clareza.\n- Marrom e terrosos: estabilidade, acolhimento.\n- Roxo: criatividade, espiritualidade.\nO significado sempre depende do contexto e da tonalidade usada.\n\n## Cabelo\nA cor do cabelo é lida numa escala de altura de tom (1 = preto, 10 = loiro clariíssimo) e em nuances (acinzentado, dourado, acobreado etc.). Na recomendação, respeita-se o TIP da estação: estações frias pedem nuances frias ou neutras; estações quentes aceitam dourados e acobreados.\n\n## Como usar no copiloto\n- A ficha segue exatamente o roteiro acima (contraste → profundidade → intensidade → temperatura → vermelhos → estação).\n- O TIP de cada estação é o rótulo do modelo de ML (Etapa 2).\n- A regra "sempre por comparação" e o respeito ao desejo de imagem da cliente entram no system prompt.\n',
  },
  {
    arquivo: "02_visagismo.md",
    titulo: "visagismo",
    conteudo:
      '---\ntema: Visagismo\nnivel: 2 (método)\nfontes: Apostila de Visagismo 1 (especialização); Apostila de Visagismo 2 (Senac); Visagismo Integrado (Philip Hallawell); Visagismo: Harmonia e Estética (Hallawell, referência de base)\nobservacao: resumo próprio, reescrito; não reproduz o material original\n---\n\n# Visagismo — resumo do método\n\n## Princípio\nVisagismo é criar uma imagem pessoal que **expresse quem a pessoa é e o que ela deseja comunicar**. A forma segue a função: primeiro entender a intenção (desejo de imagem), depois definir corte, cor, maquiagem e acessórios. O rosto comunica sensações pelas linhas e formas; o trabalho do consultor é reforçar ou equilibrar essas mensagens.\n\n## Linguagem visual: linhas e sensações\n| Linha / forma | Sensação que transmite |\n|---|---|\n| Reta vertical | força, autoridade, elegância, alongamento |\n| Reta horizontal | estabilidade, calma, alargamento |\n| Diagonal / inclinada | dinamismo, movimento, ousadia |\n| Curva | suavidade, delicadeza, acolhimento, sensualidade |\n| Ângulos marcados | firmeza, determinação |\n\n## Linhas e temperamentos\n- **Colérico:** retas verticais e ângulos; força e liderança.\n- **Sanguíneo:** diagonais e linhas inclinadas; energia e extroversão.\n- **Melancólico:** linhas curvas e verticais finas, delicadeza; sensibilidade.\n- **Fleumático:** linhas horizontais e curvas amplas; calma e estabilidade.\n(Detalhes de cada temperamento no resumo "Temperamento".)\n\n## Formatos de rosto\n| Formato | Características | Leitura / orientação geral |\n|---|---|---|\n| Oval | contorno curvo, proporcionado, testa um pouco mais larga que o queixo | equilíbrio; aceita a maioria dos cortes, óculos e decotes |\n| Redondo | largura próxima do comprimento, curvas suaves | simpatia; linhas verticais e ângulos alongam |\n| Quadrado | testa e mandíbula largas e retas | firmeza; curvas e assimetrias suavizam |\n| Retangular | alongado, laterais retas | seriedade; volume lateral e franjas encurtam |\n| Triangular (base larga) | mandíbula mais larga que a testa | estabilidade; volume no alto equilibra |\n| Triangular invertido / coração | testa larga, queixo fino | dinamismo; volume na altura do queixo equilibra |\n| Hexagonal / diamante | maçãs largas, testa e queixo estreitos | marcante; suavizar as maçãs e ampliar testa e queixo |\n\n## Proporções e partes do rosto\n- **Terços:** superior (testa: intelecto), médio (olhos e nariz: emoção), inferior (boca e queixo: ação/instinto). O terço dominante indica qual aspecto aparece primeiro; o menor pode sugerir o aspecto mais contido.\n- **Lado dominante:** um lado do rosto costuma ser mais expressivo; orienta a divisão do cabelo e a assimetria de franjas.\n- **Sobrancelhas:** moldura do olhar. Início alinhado à asa do nariz, arco próximo ao terço externo da íris e final na diagonal nariz–canto do olho. Sobrancelhas retas passam firmeza; arqueadas, suavidade.\n- **Olhos e boca:** distância, tamanho e inclinação orientam maquiagem e óculos.\n\n## Cabelo\n- **Corte:** comprimento, volume e franja trabalham as linhas do rosto (alongar, encurtar, suavizar, marcar).\n- **Cor:** segue a coloração pessoal; mechas e iluminação criam profundidade e direcionam o olhar.\n- **Finalização:** liso reforça linhas retas; ondas e cachos reforçam curvas.\n\n## Acessórios, decotes e óculos (regras gerais)\n- Repetir linhas do rosto reforça a mensagem; contrastar suaviza.\n- Rosto curvo: brincos e armações com algum ângulo trazem estrutura. Rosto anguloso: formas arredondadas suavizam.\n- Decote em V alonga o pescoço e afina o rosto; decotes redondos e canoa ampliam a região.\n- **Cor da armação:** acompanha o contraste e a cartela. Alto contraste aceita armações escuras e marcantes; baixo contraste pede tons próximos da pele e do cabelo.\n\n## Análise da pele (Hallawell)\nHallawell propõe tipos cromáticos próprios, com cor de base e temperatura. No copiloto entram só como referência complementar; o diagnóstico de cor segue o método sazonal expandido.\n\n## Como usar no copiloto\n- Fundamenta os textos C de visagismo (corte, sobrancelha, terços, perfil) e o texto A de cada formato de rosto.\n- "Desejo de imagem" é um campo obrigatório da ficha e entra no prompt de cada rascunho.\n',
  },
  {
    arquivo: "03_temperamento.md",
    titulo: "temperamento",
    conteudo:
      "---\ntema: Temperamento e personalidade\nnivel: 2 (método) + 3 (referências)\nfontes: Apostilas de Visagismo 1 e 2; Visagismo Integrado (Hallawell); Beleza Leve (Luci F. Maciel); Personal Stylist — Apostila 2\nobservacao: resumo próprio, reescrito; não reproduz o material original\n---\n\n# Temperamento — resumo\n\n## Para que serve no dossiê\nO temperamento abre o dossiê porque explica **como a pessoa age e se expressa**. Combinado ao desejo de imagem, orienta se a imagem visual deve reforçar ou equilibrar esse jeito de ser. O diagnóstico usa um temperamento **primário** e um **secundário**, mais cinco eixos em porcentagem: Pensar, Sentir, Agir, Comunicar e Determinar.\n\n## Os quatro temperamentos\n### Sanguíneo\n- Extrovertido, comunicativo, otimista, espontâneo, sociável.\n- Pontos de atenção: dispersão, impulsividade, dificuldade de rotina.\n- Tende a traços dinâmicos e expressivos, gestos amplos.\n- Linguagem visual: diagonais, cores vivas, movimento.\n\n### Colérico\n- Líder, determinado, prático, objetivo, rápido nas decisões.\n- Pontos de atenção: impaciência, autoritarismo, pouca escuta.\n- Tende a traços marcados e angulosos, postura firme.\n- Linguagem visual: retas verticais, ângulos, contraste alto.\n\n### Melancólico\n- Sensível, analítico, detalhista, profundo, criativo, perfeccionista.\n- Pontos de atenção: autocrítica, pessimismo, introspecção excessiva.\n- Tende a traços delicados e alongados.\n- Linguagem visual: linhas finas e curvas, refinamento, detalhes.\n\n### Fleumático\n- Calmo, estável, racional, diplomático, bom ouvinte.\n- Pontos de atenção: acomodação, lentidão para mudanças, pouca iniciativa.\n- Tende a traços suaves e arredondados.\n- Linguagem visual: horizontais, curvas amplas, tons suaves.\n\n## Combinações\nNinguém é de um temperamento só. O primário mostra o modo dominante e o secundário, o complemento (ex.: fleumático + sanguíneo = calma com sociabilidade). Os cinco eixos em % mostram a intensidade de cada função.\n\n## Personalidade e imagem (referências)\n- Teorias da personalidade (psicodinâmica, humanista, social-cognitiva) ajudam a entender motivações e autoimagem.\n- A imagem pessoal é um processo de **autoconhecimento**: mudar o exterior acompanha mudanças internas.\n- O consultor não rotula; usa o temperamento como ponto de partida para uma imagem coerente e autêntica.\n\n## Como usar no copiloto\n- Texto A por temperamento (características, pontos positivos e de atenção, traços físicos).\n- As 5 barras em % vêm da ficha (dados B).\n- Os rascunhos C devem conectar temperamento, desejo de imagem e as recomendações de visagismo.\n",
  },
  {
    arquivo: "04_tipologia_feminina.md",
    titulo: "tipologia feminina",
    conteudo:
      "---\ntema: Tipologia física feminina\nnivel: 2 (método)\nfontes: Apostila de Tipologia Física; Aula de Styling 2024 (Centro Europeu)\nobservacao: resumo próprio, reescrito; não reproduz o material original\n---\n\n# Tipologia física feminina — resumo\n\n## Objetivo\nIdentificar a silhueta e as proporções do corpo para escolher peças, tecidos e estampas que criem **equilíbrio visual** e atendam ao desejo de imagem, sem padrão único de corpo ideal.\n\n## Medição\n- Medidas básicas: ombro, busto, cintura e quadril (cm); também tronco × pernas.\n- **Método das varetas:** linhas imaginárias do ombro ao quadril mostram se o corpo afunila, alarga ou fica reto, e se a cintura é marcada.\n- A medida sugere a silhueta; a observação do consultor confirma.\n\n## As silhuetas\n| Silhueta | Como é | Estratégia geral |\n|---|---|---|\n| Ampulheta (X) | ombros e quadril alinhados, cintura bem marcada | valorizar a cintura, tecidos com caimento, evitar peças retas e largas demais |\n| Triângulo (A) | quadril mais largo que os ombros | chamar atenção para a parte de cima (decotes, ombros estruturados) e peças escuras e lisas embaixo |\n| Triângulo invertido (Y) | ombros mais largos que o quadril | suavizar os ombros; volume, cor e estampa na parte de baixo |\n| Retângulo (H) | ombros, cintura e quadril parecidos, pouca cintura | criar cintura (cintos, recortes, peplum), sobreposições |\n| Oval (O) | volume concentrado no meio do corpo | linhas verticais, decote em V, tecidos fluidos, evitar marcar a cintura |\n| Magro (I) | estrutura longilínea e estreita | volumes, texturas, camadas e horizontais |\n| Ideal / equilibrado | proporções harmônicas | aceita a maioria dos modelos, depende do estilo |\n\n## Proporção tronco × pernas\n- Tronco longo e pernas curtas: cintura alta, calçados na cor da calça ou da pele, peças de cima mais curtas.\n- Tronco curto e pernas longas: cintura baixa ou natural, peças de cima mais longas, cintos finos.\n\n## Pontos de atenção (dicas fixas por ponto)\n- **Parecer mais alta:** monocromia, linhas verticais, cintura alta, salto e bico fino.\n- **Parecer mais baixa:** cortes horizontais, contrastes entre partes de cima e de baixo.\n- **Suavizar ombros largos:** decote em V, mangas raglã, tecidos macios, sem ombreiras.\n- **Braços:** mangas três-quartos ou fluídas, evitar mangas que apertam.\n- **Canelas grossas:** calças retas e soltas, barras na altura certa, evitar tiras no tornozelo.\n- **Abdômen:** tecidos que não marcam, peças de cima que cobrem o quadril, estampas pequenas.\n- **Postura** (ombros caídos, cabeça projetada, hiperlordose): orientar e, quando for o caso, encaminhar a profissionais de saúde; roupas estruturadas ajudam visualmente.\n\n## Elementos e princípios de design\n- **Elementos:** linha, forma, cor, textura e padronagem (estampa).\n- **Princípios:** equilíbrio, proporção, escala, ritmo, destaque e harmonia.\n- **Escala:** tamanho de estampas e acessórios acompanha a estrutura do corpo e do rosto.\n- **Textura:** brilho e volume ampliam; foscos e lisos reduzem.\n- **Estampas:** o tamanho e o contraste da estampa acompanham o contraste pessoal.\n\n## Tecidos\n- Com caimento (seda, viscose, jersey): valorizam curvas.\n- Estruturados (alfaiataria, sarja, linho encorpado): criam forma em corpos retos.\n- Volumosos (tricô grosso, tafetá): ampliam; usar onde se quer volume.\n\n## Como usar no copiloto\n- As medidas da ficha geram a silhueta sugerida (regra; depois, ML).\n- Os pontos de atenção marcados na ficha puxam as dicas fixas desta lista.\n",
  },
  {
    arquivo: "05_tipologia_masculina.md",
    titulo: "tipologia masculina",
    conteudo:
      "---\ntema: Tipologia física e guia de estilo masculino\nnivel: 2 (método) + 3 (referências)\nfontes: Apostila de Imagem e Estilo Masculino; Consultoria de Imagem Homens (Bruna Corralo); Guia de Looks Masculinos (Ferricelli)\nobservacao: resumo próprio, reescrito; não reproduz o material original\n---\n\n# Tipologia e estilo masculino — resumo\n\n## Medição\nAltura, peso, ombro, tórax, cintura e quadril. O fluxo da sessão é o mesmo do feminino; muda a biblioteca.\n\n## Tipos físicos\n| Tipo | Como é | Apostar | Evitar |\n|---|---|---|---|\n| Trapézio | ombros e tórax mais largos que cintura e quadril, proporcional | quase tudo; peças ajustadas sem apertar | roupas muito largas que escondem a forma |\n| Triângulo invertido | ombros muito largos, cintura estreita | calças com mais estrutura, cores claras embaixo | ombreiras, listras horizontais no peito |\n| Retangular | ombros, cintura e quadril alinhados | camadas, blazers estruturados, contraste entre partes | peças muito justas e retas |\n| Triângulo | quadril e cintura mais largos que os ombros | ombros estruturados, detalhes e cores na parte de cima | calças claras e com volume |\n| Oval | volume concentrado no abdômen | linhas verticais, tecidos com caimento, peças de cima por fora com comprimento certo | peças coladas, cintos marcados, estampas grandes no tronco |\n\n## Peças-chave\n- **Camisas:** social (colarinho estruturado), casual (oxford, linho), esportiva (polo). Ombro no lugar, manga no pulso.\n- **Calças:** alfaiataria, chino, jeans. Barra sem sobrar ou com leve quebra.\n- **Blazer/paletó:** ombro alinhado, manga mostrando cerca de 1 cm do punho da camisa.\n- **Sapatos:** Oxford (mais formal), Derby, Loafer/mocassim, Monk, Brogue, Chelsea boot, tênis minimalista.\n- **Meias:** combinam com a calça (formal) ou viram destaque (casual).\n- **Cinto:** acompanha a cor e o acabamento do sapato.\n\n## Níveis de formalidade\n- **Casual:** jeans, camiseta ou polo, tênis.\n- **Esporte fino:** chino ou alfaiataria, camisa, blazer opcional, loafer ou derby.\n- **Social / passeio completo:** terno, camisa social, gravata opcional, oxford.\n- **Dress code corporativo:** segue a cultura da empresa; na dúvida, um nível acima do grupo.\n\n## Montagem de mala\nBase de neutros que combinam entre si, poucas peças de destaque, um calçado versátil e um formal, e tecidos que amassam pouco.\n\n## Como usar no copiloto\n- Modo masculino da ficha: medidas próprias e tipo sugerido.\n- Guia de estilo do Pacote Completo usa estas listas como texto fixo; composição de looks e lista de compras são personalizadas.\n",
  },
  {
    arquivo: "06_estilos_universais.md",
    titulo: "estilos universais",
    conteudo:
      "---\ntema: Estilos universais e análise de estilo\nnivel: 2 (método) + 3 (referências)\nfontes: Apostila de Imagem e Estilo Masculino; Personal Stylist — Apostila 1; Consultoria de Imagem Homens; Fundamentos da Consultoria de Imagem\nobservacao: resumo próprio, reescrito; não reproduz o material original\n---\n\n# Estilos universais — resumo\n\n## Estilo × moda\nModa é passageira e coletiva; **estilo** é a forma pessoal e duradoura de se vestir, ligada à personalidade e aos objetivos. A análise de estilo compara o **estilo detectado** (como a pessoa se veste hoje) com o **estilo desejado** (como quer ser percebida). Normalmente há um estilo principal e um ou dois secundários.\n\n## Os 7 estilos\n| Estilo | Mensagem | Peças e características |\n|---|---|---|\n| Esportivo / natural | praticidade, conforto, espontaneidade | jeans, malhas, tênis, tecidos naturais, pouca maquiagem |\n| Elegante | sofisticação, requinte, discrição | alfaiataria impecável, neutros, tecidos nobres, acessórios delicados |\n| Tradicional / clássico | seriedade, confiança, organização | peças atemporais, cortes retos, cores sóbrias, pouca variação |\n| Romântico | delicadeza, feminilidade/suavidade | curvas, babados, rendas, florais, tons suaves |\n| Dramático / urbano | impacto, poder, modernidade | linhas fortes, contraste, preto, peças estruturadas |\n| Sedutor / sensual | autoconfiança, sensualidade | peças que marcam o corpo, decotes, fendas, tecidos com brilho |\n| Criativo | originalidade, ousadia | mistura de estampas, cores e texturas, peças autorais e vintage |\n\n## Dress code social\n- **Esporte / casual:** livre, confortável.\n- **Esporte fino:** arrumado sem ser formal.\n- **Passeio / social:** vestido ou conjunto elegante; terno.\n- **Black tie / traje de gala:** longo; smoking.\nHorário e local influenciam cores e tecidos: dia pede tons mais claros e foscos; noite aceita brilho e cores profundas.\n\n## Como usar no copiloto\n- A análise de estilo do Pacote Completo usa esta tabela como texto fixo.\n- O estilo desejado entra, junto com o temperamento e o desejo de imagem, nos rascunhos da IA.\n",
  },
  {
    arquivo: "07_maquiagem_acessorios.md",
    titulo: "maquiagem acessorios",
    conteudo:
      "---\ntema: Maquiagem, acessórios e óculos\nnivel: 3 (referências) + biblioteca\nfontes: Técnicas de Maquiagem, Visagismo e Imagem Pessoal (UniCesumar); Apostilas de Coloração Pessoal; dossiê guia (padrão das páginas)\nobservacao: resumo próprio, reescrito; não reproduz o material original\n---\n\n# Maquiagem, acessórios e óculos — resumo\n\n## Maquiagem por cartela\n- A maquiagem **repete os pigmentos naturais** da pessoa: subtom e intensidade da estação definem o tom de base, blush, batom e sombras.\n- **Verão:** rosados, malvas, acabamentos acetinados, pouca saturação.\n- **Outono:** terrosos, pêssegos queimados, tijolos, acabamentos foscos.\n- **Inverno:** cores puras e profundas, vermelhos frios, contraste, acabamentos com brilho.\n- **Primavera:** corais, pêssegos vivos, dourados, frescor.\n- **Quantidade de cor:** estações suaves pedem menos cores e mais esfumado; estações brilhantes aceitam um ponto de cor forte.\n- Os produtos (marca + nome da cor + categoria + cartela) ficam num catálogo que o consultor atualiza.\n\n## Maquiagem corretiva e por formato de rosto\n- **Luz** (tons claros) traz para frente e amplia; **sombra** (tons escuros) afasta e afina.\n- Rosto redondo: contorno nas laterais para alongar. Quadrado: suavizar os ângulos da mandíbula e da testa. Retangular: blush na horizontal para encurtar. Triangular invertido: suavizar a testa e iluminar o queixo.\n- Olhos: sombra esfumada para fora alonga; iluminar o canto interno afasta olhos próximos.\n- Sobrancelhas: seguir a proporção do visagismo; preencher falhas com sombra próxima da cor dos fios.\n- Pele: preparar e hidratar, base no subtom exato, corretivo pontual.\n\n## Acessórios\n- **Metais:** seguem a estação (ver Coloração pessoal).\n- **Escala:** acessórios proporcionais ao rosto e ao corpo.\n- **Forma:** linhas do rosto guiam brincos e colares (repetir para reforçar, contrastar para equilibrar).\n- **Pedras:** tons da cartela (ex.: frias e brilhantes no Inverno; terrosas no Outono).\n\n## Óculos\n- Armação contrasta ou equilibra o formato do rosto.\n- Largura próxima da parte mais larga do rosto; ponte adequada ao nariz.\n- Cor da armação segue a cartela; a espessura e o escurecimento acompanham o contraste pessoal.\n\n## Estampas\n- Tamanho da estampa acompanha a estrutura (pequena/média/grande).\n- Contraste da estampa acompanha o contraste pessoal (baixo, médio, alto).\n- Animal print e geométricos seguem as cores e o acabamento da estação.\n\n## Como usar no copiloto\n- Páginas de maquiagem, metais, pedras, estampas e óculos do dossiê usam estes textos-base, ajustados automaticamente pela cartela e pelo contraste.\n",
  },
  {
    arquivo: "08_styling_atendimento.md",
    titulo: "styling atendimento",
    conteudo:
      "---\ntema: Styling, composição de looks e atendimento\nnivel: 3 (referências)\nfontes: Aula de Styling 2024 (Centro Europeu); Guia de Looks Masculinos; Manual da Consultora de Imagem (Érica Minchin); Fundamentos da Consultoria de Imagem; Empreendedorismo em Consultoria de Imagem; Consultoria de Cores\nobservacao: resumo próprio, reescrito; não reproduz o material original\n---\n\n# Styling e atendimento — resumo\n\n## Composição de looks\n- Começar pelo **objetivo** (ocasião, mensagem, conforto).\n- **Regra das cores:** uma base neutra e até duas cores de destaque por look.\n- **Proporção:** peça ampla combinada com peça ajustada; marcar ou não a cintura conforme a silhueta.\n- **Terceira peça** (blazer, colete, cardigã, lenço) eleva o nível do look.\n- **Mistura de estampas:** repetir uma cor entre elas e variar a escala.\n- **Truques rápidos:** dobrar a manga, meia-prensa da camisa, cinto para criar cintura, monocromia para alongar.\n\n## Guarda-roupa funcional\n- **Peças-base:** neutros da cartela que combinam entre si.\n- **Peças de destaque:** cor, estampa ou textura que trazem estilo.\n- **Detox de guarda-roupa:** manter o que veste bem, está na cartela e conversa com o estilo; ajustar, doar ou descartar o resto.\n- **Personal shopping:** lista de compras por prioridade e categoria, com base nas lacunas encontradas.\n\n## Medidas de caimento (referência rápida)\n- Calça social: barra toca levemente o sapato.\n- Manga de blazer: deixa aparecer um pouco do punho da camisa.\n- Bermuda: acima do joelho.\n- Ombro da peça alinhado ao ombro do corpo.\n\n## Cores na comunicação\n- As cores do guarda-roupa e da identidade digital (perfil, redes) devem conversar com a mensagem desejada.\n- Proporção de cor no look: grandes áreas em cores neutras, pequenas áreas em cores intensas.\n\n## Atendimento ao cliente\n- **Etapas típicas:** contato inicial → questionário pré-sessão (rotina, objetivos, desafios, desejo de imagem) → sessões de análise → entrega do dossiê → acompanhamento.\n- **Perguntas úteis:** o que quer transmitir; como se vê hoje; ocasiões mais frequentes; peças que ama e que evita; orçamento e rotina.\n- **Postura:** escuta ativa, linguagem acolhedora, sem julgamentos, explicar o porquê de cada recomendação.\n- **Promessa do serviço:** economia de tempo e dinheiro, mais segurança e autoconhecimento.\n\n## Como usar no copiloto\n- Base para o chat responder dúvidas práticas do consultor.\n- Orienta o questionário pré-sessão e o tom da persona (acolhedor, técnico e claro).\n",
  },
];
